# Generated by Django 4.0.1 on 2022-02-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_category_likes_category_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
